services:
  - type: web
    name: docscope-backend
    env: python
    pythonVersion: 3.12.6
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
